/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kasir;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author yaniyan
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admin
     */

    public Admin() {
        initComponents();
        panelChart.setLayout(new BorderLayout()); 
        loadChart();
    }

   private void loadChart() {
    LineChart chart = new LineChart();

    // kasih preferred size supaya scroll aktif

    JScrollPane scrollPane = new JScrollPane(chart,
        JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

    panelChart.setLayout(new BorderLayout());
    panelChart.removeAll();
    panelChart.add(scrollPane, BorderLayout.CENTER);
    panelChart.revalidate();
    panelChart.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelChart = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(20000, 20000));
        setPreferredSize(new java.awt.Dimension(1740, 960));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1740, 960));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelChart.setBackground(new java.awt.Color(255, 255, 255));
        panelChart.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pemasukkan Dan penjualan"));
        panelChart.setLayout(new java.awt.BorderLayout());
        jPanel2.add(panelChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 1690, 370));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1740, 960));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelChart;
    // End of variables declaration//GEN-END:variables
}
